path fix

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -37,9 +37,16 @@ jobs:
           fi
 
       - name: Decode GPG file from secret
+        working-directory: OneSignalSDK
         run: |
           echo "$SDK_SIGNING_SECRET_KEY_RING_ENCODED" | base64 -d > "$GPG_FILE_NAME"
-          echo "signing.secretKeyRingFile=$(pwd)/$GPG_FILE_NAME" >> $GITHUB_ENV
+          echo "GPG_FILE_PATH=$(pwd)/$GPG_FILE_NAME" >> $GITHUB_ENV
+
+      - name: Verify GPG file
+        working-directory: OneSignalSDK
+        run: |
+          ls -lh "$GPG_FILE_PATH"
+          gpg --list-packets "$GPG_FILE_PATH" || echo "Invalid key file!"
 
       - name: Extract SDK_VERSION from gradle.properties
         id: version
@@ -57,7 +64,7 @@ jobs:
           ./gradlew publishToMavenLocal --no-configuration-cache \
             -Psigning.keyId="$SDK_SIGNING_KEY_ID" \
             -Psigning.password="$SDK_SIGNING_PASSWORD" \
-            -Psigning.secretKeyRingFile="$(pwd)/$GPG_FILE_NAME"
+            -Psigning.secretKeyRingFile="$GPG_FILE_PATH"
         working-directory: OneSignalSDK
 
       - name: Publish to Maven Central
@@ -67,8 +74,8 @@ jobs:
             -PmavenCentralPassword="$MAVEN_PASSWORD" \
             -Psigning.keyId="$SDK_SIGNING_KEY_ID" \
             -Psigning.password="$SDK_SIGNING_PASSWORD" \
-            -Psigning.secretKeyRingFile="$(pwd)/$GPG_FILE_NAME"
-        working-directory: OneSignalSDK
+            -Psigning.secretKeyRingFile="$GPG_FILE_PATH"
+      - working-directory: OneSignalSDK
 
       - name: Get latest merged rel/* PR into main
         id: fetch_pr
